### ISSUE TITLE
Does this work with Elixir v1.11?

### ISSUE THREAD

**Issue by SwenSchaeferjohann** [suazithustra/arangox#1]
Elixir version 1.11 was released mid last year. Also Arango is still listing arangox as driver option.
![image](https://user-images.githubusercontent.com/42959314/107538728-91465600-6bc4-11eb-966d-721f7d46d92f.png)

Any info @suazithustra ? Greatly appreciated.

**Comment by suazithustra** [comment]
tested it with 1.11.3 and latest arangodb docker image, works just fine
