### ISSUE TITLE
missing actual usage example

### ISSUE THREAD

**Issue by AbducteeZero** [suazithustra/arangox#3]
Can you please add the most basic AQL query call in the examples.
insert a doc and recall it

**Comment by AbducteeZero** [comment]
yeah i'm going crazy.  I can't figure out how to use this.

**Comment by AbducteeZero** [comment]
OK, I started writing my own little wrapper:
defmodule Arango do
  def run(query: query, args: args) do
    Arangox.run(:arangodb, fn c ->
      stream = Arangox.cursor(c, query, args, timeout: 15_000)
      Enum.to_list(stream)
    end)
  end

  def replace_doc(collection: collection, id: id, doc: doc) do
    doc_with_key = Map.merge(doc, %{_key: id})

    run(
      query: "REPLACE @doc IN #{collection}",
      args: [doc: doc_with_key]
    )
  end

  def create_collection(collection_name) do
    Arangox.post!(:arangodb, "_api/collection", %{name: collection_name})
  end
end

something like this works for me:
Arango.replace_doc(collection: "people", id: "3825", doc: %{name: "new name"})
but
Arango.replace_doc(collection: "people", id: "3825", doc: %{name: "new name", updated_at: DateTime.utc_now})
yields:
** (Protocol.UndefinedError) protocol Enumerable not implemented for ~U[2022-10-28 21:52:43.922671Z] of type DateTime (a struct). This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Xandra.Page, Xandra.PageStream
    (elixir 1.14.1) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.14.1) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.14.1) lib/enum.ex:4307: Enum.map/2
    (velocy 0.1.6) lib/velocy_pack/encode.ex:244: VelocyPack.Encode.encode_map/2
    (velocy 0.1.6) lib/velocy_pack/encode.ex:250: anonymous fn/3 in VelocyPack.Encode.encode_map/2
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (velocy 0.1.6) lib/velocy_pack/encode.ex:246: VelocyPack.Encode.encode_map/2
    iex:45: (file)

any ideas?
Thanks

**Comment by AbducteeZero** [comment]
I can't be the only one trying to use this library to get data IN and OUT of the database.  please help, am I off in a totally wrong direction?

**Comment by suazithustra** [comment]
We have this in the readme:

```elixir
iex> Arangox.transaction(conn, fn c ->
iex>   stream =
iex>     Arangox.cursor(
iex>       c,
iex>       "FOR i IN [1, 2, 3] FILTER i == 1 || i == @num RETURN i",
iex>       %{num: 2},
iex>       properties: [batchSize: 1]
iex>     )
iex>
iex>   Enum.reduce(stream, [], fn resp, acc ->
iex>     acc ++ resp.body["result"]
iex>   end)
iex> end)
{:ok, [1, 2]}
```

Is this not working in your environment?

**Comment by AbducteeZero** [comment]
That is working for me, thanks.  As a newbie landing here it's just not obvious that that is the primary interface.  "cursor" threw me off.  Doing an INSERT through a function called cursor feels odd.  Maybe I'm too new to arango as well.  I suspect it would still help future noobs to have a more realistic example of inserting a map and recalling it.

**Comment by suazithustra** [comment]
That's understandable. The reason why AQL must go through a cursor is because that's the only way arangodb's api consumes AQL and this library only handles 'communication' with said api at the moment. If all you're trying to do is insert a document and retrieve it then AQL isn't strictly necessary, there are other endpoints for that:

```elixir
Arangox.post(conn, "/_api/document/#{collection}", %{my: "map"})
Arangox.get(conn, "/_api/document/#{collection}/#{key}"
```

You should keep arangodb's swagger docs open in the dashboard for reference as you're using this lib for now until we add more convenience functions.
