### ISSUE TITLE
Can't connect  :noproc

### ISSUE THREAD

**Issue by julienmarie** [suazithustra/arangox#9]
I can't connect to the Arangodb instance. Did I miss something?

Arango version: 3.12.2 running on Docker
Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]
Elixir 1.17.2 (compiled with Erlang/OTP 27)

```
iex(2)> options = [
...(2)>   endpoints: "http://unraid:8529",
...(2)>   pool_size: 10
...(2)> ]
[endpoints: "http://unraid:8529", pool_size: 10]
iex(3)> Arangox.start_link(options)
{:ok, #PID<0.942.0>}
[error] Arangox.Connection (#PID<0.949.0>) failed to connect: ** (Arangox.Error) :noproc
[error] Arangox.Connection (#PID<0.947.0>) failed to connect: ** (Arangox.Error) :noproc
[error] Arangox.Connection (#PID<0.946.0>) failed to connect: ** (Arangox.Error) :noproc
```

**Comment by julienmarie** [comment]
It seems it is related to Velocy. Using GunClient works.

**Comment by suazithustra** [comment]
VelocyStream was removed in 3.12. Arangox's default client will be Mint in the next release.
